<?php
require_once __DIR__ . '/../config/database.php';
include '../includes/header.php';

$berita_id = isset($_GET['berita']) ? (int)$_GET['berita'] : 0;
$berita_detail = null;
if ($berita_id > 0) {
    $st=$conn->prepare('SELECT * FROM berita WHERE id=? LIMIT 1'); $st->bind_param('i',$berita_id); $st->execute(); $berita_detail=$st->get_result()->fetch_assoc();
}
$pengumuman_data=$conn->query('SELECT * FROM pengumuman ORDER BY tanggal DESC,id DESC')->fetch_all(MYSQLI_ASSOC);
$berita_data=$conn->query('SELECT * FROM berita ORDER BY tanggal DESC,id DESC')->fetch_all(MYSQLI_ASSOC);
$agenda_data=$conn->query('SELECT * FROM agenda ORDER BY tanggal_kegiatan ASC,id ASC')->fetch_all(MYSQLI_ASSOC);
?>
<link rel="stylesheet" href="../css/informasi.css?v=20260929">
<div class="informasi-page">
<?php if($berita_detail): ?>
<article class="berita-detail-page"><div class="informasi-container"><a href="informasi.php" class="berita-detail-back">← Kembali ke Informasi</a><div class="berita-detail-date">Berita Sekolah · <?= date('d M Y',strtotime($berita_detail['tanggal'])) ?></div><h1><?= e($berita_detail['judul']) ?></h1><?php if($berita_detail['gambar']): ?><div class="berita-detail-image"><img src="../assets/berita/<?= e($berita_detail['gambar']) ?>" alt="<?= e($berita_detail['judul']) ?>"></div><?php endif; ?><div class="berita-detail-content"><?= nl2br(e($berita_detail['isi'])) ?></div></div></article>
<?php else: ?>
<section class="informasi-hero"><div class="informasi-container"><div class="informasi-hero-content"><span class="informasi-eyebrow">INFORMASI SEKOLAH</span><h1>Informasi & Kabar<br><span>Terkini Sekolah</span></h1><p>Temukan pengumuman resmi, berita terbaru, dan agenda kegiatan sekolah dalam satu halaman.</p></div><div class="informasi-hero-decoration"><div class="info-circle info-circle-one"></div><div class="info-circle info-circle-two"></div><div class="info-circle info-circle-three"></div><div class="info-hero-card"><span>UPDATE</span><strong>Informasi<br>Sekolah</strong><small>Selalu diperbarui</small></div></div></div></section>
<section class="informasi-section informasi-announcement"><div class="informasi-container"><div class="informasi-section-heading"><div><span class="informasi-label">PENGUMUMAN</span><h2>Pengumuman Resmi</h2><p>Informasi penting dan pemberitahuan resmi dari sekolah untuk seluruh warga sekolah.</p></div><div class="informasi-heading-line"></div></div><div class="informasi-announcement-grid"><?php if($pengumuman_data): foreach($pengumuman_data as $p): ?><article class="informasi-announcement-card"><div class="informasi-announcement-icon">▤</div><div class="informasi-card-date">Diposting · <?= date('d M Y',strtotime($p['tanggal'])) ?></div><h3><?= e($p['judul']) ?></h3><p><?= nl2br(e($p['isi'])) ?></p></article><?php endforeach; else: ?><div class="informasi-empty"><span>Tidak ada pengumuman</span><p>Belum ada pengumuman resmi saat ini.</p></div><?php endif; ?></div></div></section>
<section class="informasi-section informasi-news"><div class="informasi-container"><div class="informasi-section-heading"><div><span class="informasi-label">BERITA</span><h2>Berita Terkini</h2><p>Kabar terbaru mengenai kegiatan, pencapaian, dan berbagai aktivitas sekolah.</p></div><div class="informasi-heading-line"></div></div><div class="informasi-news-grid"><?php if($berita_data): foreach($berita_data as $b): ?><a href="informasi.php?berita=<?= (int)$b['id'] ?>" class="informasi-news-card-link"><article class="informasi-news-card"><div class="informasi-news-image"><?php if($b['gambar']): ?><img src="../assets/berita/<?= e($b['gambar']) ?>" alt="<?= e($b['judul']) ?>"><?php endif; ?></div><div class="informasi-news-content"><div class="informasi-card-date">Diposting · <?= date('d M Y',strtotime($b['tanggal'])) ?></div><h3><?= e($b['judul']) ?></h3><p><?= e(mb_strimwidth(strip_tags($b['isi']),0,180,'...')) ?></p></div></article></a><?php endforeach; else: ?><div class="informasi-empty"><span>Tidak ada berita</span><p>Belum ada berita terbaru.</p></div><?php endif; ?></div></div></section>
<section class="informasi-section informasi-agenda"><div class="informasi-container"><div class="informasi-section-heading"><div><span class="informasi-label">AGENDA</span><h2>Agenda Mendatang</h2><p>Jadwal kegiatan sekolah yang akan berlangsung dalam waktu mendatang.</p></div><div class="informasi-heading-line"></div></div><div class="informasi-agenda-wrapper"><div class="informasi-agenda-header"><div>Tanggal</div><div>Agenda / Kegiatan</div><div>Lokasi</div><div>Keterangan</div></div><?php foreach($agenda_data as $a): ?><div class="informasi-agenda-row"><div><?= date('d M Y',strtotime($a['tanggal_kegiatan'])) ?></div><div><?= e($a['judul']) ?></div><div><?= e($a['lokasi']) ?></div><div><?= e($a['keterangan']) ?></div></div><?php endforeach; ?></div></div></section>
<?php endif; ?></div>
<?php include '../includes/footer.php'; ?>
